server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurants/**

        - id: reservation-service-auth
          uri: lb://reservation-service
          predicates:
            - Path=/api/auth/**

        - id: reservation-service-reservations
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**

        - id: client-web
          uri: lb://client-web
          predicates:
            - Path=/api/search/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}